const CONFIG = {
    introTitle: 'bạn oiii!',
    introDesc: `bấm vào bên dưới nhé`,
    btnIntro: 'đây này',
    title: 'love you 😙',
    desc: ' bạn có thích mình không?? ',
    btnYes: 'rất thích <33',
    btnNo: 'có :3',
    question:'tại sao lại thích tớ vậy chứ hjhj',
    btnReply: 'gửi câu trả lời',
    reply: 'yêu thì yêu mà không yêu thì yêu hihi',
    mess: 'cảm ơn. tớ cũng thích cậu😘😘',
    messDesc: 'đi vòng quanh thế giới nhé!!.',
    btnAccept: 'Okiiiii lun <3',
    messLink: https://www.facebook.com/hoang01.282301/
